### ISSUE TITLE
Help with mongorestore

### ISSUE THREAD

**Issue by mcury1985** [themattman/mongodb-raspberrypi-binaries#1]
- Raspberry Pi 4b 4GB running Ubuntu 20.04 64 bits.
- Followed the steps as per documentation but changed the following command.

./mongod --dbpath /data/db/ts_test_db --fork --logpath /data/db/ts_test_db_log/ts_test_db.log --port 27017

The process starts successfully.
`ubuntu@rpi4:~/mdb-binaries$ ./mongod --dbpath /data/db/ts_test_db --fork --logpath /data/db/ts_test_db_log/ts_test_db.log --port 27017
about to fork child process, waiting until server is ready for connections.
forked process: 9033
child process started successfully, parent exiting`

After that, graylog also starts successfully and I can login, but all my settings are lost.
The problem is that I can't run mongorestore to restore my database, is there anyway to do this with this release?

Thanks in advance.

**Comment by mcury1985** [comment]
Oh, you need to have another version of mongod installed, but you can stop/disable that service.

Then, to run mongorestore, you can create a folder inside /data/db/ts_test_db/graylog and use the following command:
`ubuntu@rpi4:/data/db/ts_test_db/graylog$ mongorestore -d graylog /home/ubuntu/graylog/`
Assuming that your backup db is inside /home/ubuntu/graylog.

Everything is working.. Now I have mongodb 6.0.5 up and running.
Graylog 5.0.6 up and running.

Thanks a lot for your work on this.. Really appreciated.

**Comment by themattman** [comment]
I'm glad to hear you resolved this.
