### ISSUE TITLE
error while loading shared libraries: libcrypto.so.1.1:

### ISSUE THREAD

**Issue by elvecinodelseptimo** [themattman/mongodb-raspberrypi-binaries#12]
**Describe the bug**
Ran instructions provided. This one causes an error:
./mongod --dbpath /data/db/test_db --fork --logpath /data/db/test_db/mongod.log --port 28080
Missing library:
./mongod: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory

**To Reproduce**
Running instructions provided (adding sudo in front of  mkdir -p /data/db/test_db and touch /data/db/test_db/mongod.log) on newly installed Raspberry Pi OS 64 bit

Linux raspberrypi 6.6.20+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.20-1+rpt1 (2024-03-07) aarch64 GNU/Linux
Model           : Raspberry Pi 4 Model B Rev 1.5, 2Gb RAM

Tried solutions proposed elsewhere:
sudo apt install libssl ==> E: Unable to locate package libssl
same with 
sudo apt install openssl-libs
sudo apt install openssl-dev

**Comment by tortxoFFoxtrot** [comment]
You need to download the included libc++…so file as well and IIRC place it in /usr/bin

**Comment by tortxoFFoxtrot** [comment]
Type the command: `openssl version`

I guess you have version 3?

**Comment by elvecinodelseptimo** [comment]
Yes

OpenSSL 3.0.11 19 Sep 2023 (Library: OpenSSL 3.0.11 19 Sep 2023)

**Comment by elvecinodelseptimo** [comment]
Thanks a lot. Could you indicate how to do this?
You need to download the included libc++…so file as well and IIRC place it in /usr/bin

**Comment by tortxoFFoxtrot** [comment]
> Yes
> 
> OpenSSL 3.0.11 19 Sep 2023 (Library: OpenSSL 3.0.11 19 Sep 2023)

Ok, try `sudo apt install libssl-dev` should install openssl 1.1 library I think, your problem seems like you are missing openssl 1.1 library.

**Comment by elvecinodelseptimo** [comment]
executed that instruction. Seems to successfully install something.
error at the start remains though.
./mongod: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory

**Comment by tortxoFFoxtrot** [comment]
Ok, your error is definitely that the library for openssl 1.1 does not exist. A lot of OS have moved to 3 now and are not shipping with 1.1 any longer. Need to work out how to install libssl v1.1 in your distro, which should then either put or link that file somewhere like /usr/lib or /usr/local/lib

**Comment by tortxoFFoxtrot** [comment]
You could try `sudo apt install libssl1.1-dev` to see if that will force install 1.1 for you

**Comment by elvecinodelseptimo** [comment]
E: Unable to locate package libssl1.1-dev
E: Couldn't find any package by glob 'libssl1.1-dev'

But without the -dev it did install. Now the instruction seems to be working:

 ./mongod --dbpath /data/db/test_db --fork --logpath /data/db/test_db/mongod.log --port 28080
about to fork child process, waiting until server is ready for connections.
forked process: 35822
child process started successfully, parent exiting

Fingers crossed. Thanks a lot.

**Comment by tortxoFFoxtrot** [comment]
Sweet yea that’s the ticket!

**Comment by tototomate123** [comment]
Well, I got the same bug.
im on 
Ubuntu 24.04 LTS aarch64
Kernel 6.8.0-1004-raspi
Raspberry Pi 4 Model B Rev 1.2 4GB

when i try to run `sudo apt install libssl1.1-dev`
i get the same error:
```
E: Unable to locate package libssl1.1-dev
E: Couldn't find any package by glob 'libssl1.1-dev'
```
(also tried it without the dev, the 1.1 and so on)
and also looked on ubuntu packages: 
https://packages.ubuntu.com/focal/arm64/libssl1.1/download

but there is just no download link for it. 
do i *really* need Rasperry Pi OS for it to run?

**Comment by tototomate123** [comment]
```
curl -O http://launchpadlibrarian.net/475575244/libssl1.1_1.1.1f-1ubuntu2_arm64.deb
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_arm64.deb 
```
worked for me, just wanted to share this! works for me now too!

**Comment by tortxoFFoxtrot** [comment]
> ```
> curl -O http://launchpadlibrarian.net/475575244/libssl1.1_1.1.1f-1ubuntu2_arm64.deb
> sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_arm64.deb 
> ```
> 
> worked for me, just wanted to share this! works for me now too!

1.1.1f is old, I don’t recommend it, many security fixes since.

**Comment by themattman** [comment]
Closing as this appears to be resolved. For reference #2 is a duplicate. Thanks everyone for your help!

**Comment by tototomate123** [comment]
> 1.1.1f is old, I don’t recommend it, many security fixes since.

i now installed this version: `libssl1.1_1.1.1n-0+deb11u5_arm64`
(http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.1_1.1.1n-0+deb11u5_arm64.deb)
do you think thats a better choice?

**Comment by themattman** [comment]
@tototomate123 that's the most recent package I can see distributed on debian, so that appears best to me.

**Comment by Thijxx** [comment]
For future reference, when running Ubuntu 22.04 picked in the Raspberry Pi imager none of the above will work. There is no `libssl1.1-dev`, no `libssl1.1`, no `libssl-dev` and the package mentioned by @tototomate123 above results in an `Illegal instruction (core dumped)` message. Also the earlier mentioned direct download of SSL1.1 that worked for him does not work for Ubuntu 22.04.

I suppose Raspbian will also move away from SSL1.1 so I don't know what to do, seems like no Mongo on a Pi again

**Comment by tortxoFFoxtrot** [comment]
> For future reference, when running Ubuntu 22.04 picked in the Raspberry Pi imager none of the above will work. There is no `libssl1.1-dev`, no `libssl1.1`, no `libssl-dev` and the package mentioned by @tototomate123 above results in an `Illegal instruction (core dumped)` message. Also the earlier mentioned direct download of SSL1.1 that worked for him does not work for Ubuntu 22.04.
> 
> I suppose Raspbian will also move away from SSL1.1 so I don't know what to do, seems like no Mongo on a Pi again (tested on Pi5)

What pi are you using?

**Comment by Thijxx** [comment]
> > For future reference, when running Ubuntu 22.04 picked in the Raspberry Pi imager none of the above will work. There is no `libssl1.1-dev`, no `libssl1.1`, no `libssl-dev` and the package mentioned by @tototomate123 above results in an `Illegal instruction (core dumped)` message. Also the earlier mentioned direct download of SSL1.1 that worked for him does not work for Ubuntu 22.04.
> > I suppose Raspbian will also move away from SSL1.1 so I don't know what to do, seems like no Mongo on a Pi again (tested on Pi5)
> 
> What pi are you using?

Sry, I was just adding the Pi5 part while you were typing I think :)
I did use the mentioned Pi5 compatible version form your binaries.
Meanwhile I did run the docker version and it looks fine so that may be my backup for now.

**Comment by tortxoFFoxtrot** [comment]
Ahah not my bins, I can't steal old mates thunder 😂

I know they deprecated libssl1.1-dev but I wonder if now they have removed libssl1.1 as well in that case?

I wonder if MongoDB 7 can be built targeting OpenSSL 3 is this possible @themattman?

**Comment by Thijxx** [comment]
> Ahah not my bins, I can't steal old mates thunder 😂
> 
> I know they deprecated libssl1.1-dev but I wonder if now they have removed libssl1.1 as well in that case?
> 
> I wonder if MongoDB 7 can be built targeting OpenSSL 3 is this possible @themattman?

I may have switched the Pi4 and Pi5 versions around resulting in the illegal instruction, I will double check and then test if it starts

**Comment by tortxoFFoxtrot** [comment]
> > Ahah not my bins, I can't steal old mates thunder 😂
> > I know they deprecated libssl1.1-dev but I wonder if now they have removed libssl1.1 as well in that case?
> > I wonder if MongoDB 7 can be built targeting OpenSSL 3 is this possible @themattman?
> 
> I may have switched the Pi4 and Pi5 versions around resulting in the illegal instruction, I will double check and then test if it starts

Yah that message usually suggests the wrong architecture bin but pi4 and pi5 are both arm64 so I think it would not matter in this case

**Comment by Thijxx** [comment]
> > > Ahah not my bins, I can't steal old mates thunder 😂
> > > I know they deprecated libssl1.1-dev but I wonder if now they have removed libssl1.1 as well in that case?
> > > I wonder if MongoDB 7 can be built targeting OpenSSL 3 is this possible @themattman?
> > 
> > 
> > I may have switched the Pi4 and Pi5 versions around resulting in the illegal instruction, I will double check and then test if it starts
> 
> Yah that message usually suggests the wrong architecture bin but pi4 and pi5 are both arm64 so I think it would not matter in this case, assuming of course your jammy build is a 64bit one but I think it must be eh? I think jammy dropped 32bit builds IIRC

The Pi4 version starts, so in this case the Illegal instruction message may have been a Pi4 vs Pi5 issue. I took another Pi4 and the latest Pi4 binary just runs, no SSL issue or anything, so yeah, I don't know, I was expecting the SSL issue again, lol.
