### ISSUE TITLE
7.0.12

### ISSUE THREAD

**Issue by thisIsNotTheFoxUrLookingFor** [themattman/mongodb-raspberrypi-binaries#15]
In the interim I have built v7.0.12 for rpi 4 with the caveat being that I have only built mongod and not mongo or mongos. My little pi struggled just to build mongod lol, but if anyone wants it, it is here: [https://download.foxtrot.blog/mongod.pi4.r7.0.12.tar.gz](https://download.foxtrot.blog/mongod.pi4.r7.0.12.tar.gz)

I have update my unifi docker image to include the latest mongod v7.0.12. it looks to me like they are prepping to release v8

This is obviously not an issue, I was unsure how to make it something other than an issue, apologies.

**Comment by tortxoFFoxtrot** [comment]
Thanks man, and yah tell me about it! Just building mongod used like 50GB or something ridiculous! There is no way I could do the full devcore with my disk space, madness!

**Comment by themattman** [comment]
The latest [7.0.14](https://github.com/themattman/mongodb-raspberrypi-binaries/releases/tag/r7.0.14-rpi-unofficial) is now up which supersedes 7.0.12.
