### ISSUE TITLE
libcrypto.so.1.1

### ISSUE THREAD

**Issue by houshangaziziaccelleran** [themattman/mongodb-raspberrypi-binaries#2]
Hi
I get:
```
```

houshang@houshang-desktop:~$ /home/houshang/mdb-binaries/mongod --dbpath /data/db/ts_test_db --fork --logpath /data/db/ts_test_db_log --port 28080
/home/houshang/mdb-binaries/mongod: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
houshang@houshang-desktop:~$ /home/houshang/mdb-binaries/mongod  --port 28080
/home/houshang/mdb-binaries/mongod: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
houshang@houshang-desktop:~$ 
```

```

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**MongoDB (please complete the following information):**
  - Version: [e.g. 6.2.0]

**Raspberry Pi Device (please complete the following information):**
 - Raspberry Pi Hardware Version: [e.g. 4B]
 - OS: [e.g. Raspberry Pi OS, Debian]
 - Version [e.g. 11]
 - System Version [e.g. 32-bit, 64-bit]

**Compilation Machine (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu]
 - Version [e.g. 10, 20.04]

**Additional context**

**Comment by themattman** [comment]
Hi @houshangaziziaccelleran,

Can you clarify which release you are using? I could not reproduce this issue with the latest [r6.0.7 release](https://github.com/themattman/mongodb-raspberrypi-binaries/releases/tag/r6.0.7-rpi-unofficial) on a clean install of 64-bit Raspberry Pi OS Desktop. Please fill out as many fields in the template to get a better answer.

**Comment by 760ceb3b9c0ba4872cadf3ce35a7a494** [comment]
i think recent versions of ubuntu dont ship libssl v1.1 anymore which mongodb depends on. you can fix this by installing the debian version
```sh
wget http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.1_1.1.1n-0+deb11u5_arm64.deb
dpkg -i libssl1.1*.deb
```

**Comment by rgillan** [comment]
the libssl install above solved our same issue on Ubuntu 23/RPi 4 thank you.

**Comment by Lefuneste83** [comment]
FYI on a Raspberry Pi 5 with latest bookworm Raspberry Pi OS, I can just do "apt install libssl1.1" to go through the error message.
