### ISSUE TITLE
ERROR: child process failed, exited with 1

### ISSUE THREAD

**Issue by DuoBelt** [themattman/mongodb-raspberrypi-binaries#4]
mario@raspberrypi:~/mdb-binaries $ sudo ./mongod --dbpath /data/db/ts_test_db --fork --logpath /data/db/ts_test_db_log --port 28080
about to fork child process, waiting until server is ready for connections.
forked process: 4765
ERROR: child process failed, exited with 1
To see additional information in this output, start without the "--fork" option.

**Comment by themattman** [comment]
1. Based on your invocation, I would guess that you followed the incorrect steps I published. Check the repo's README again and follow the current steps. The logpath should be a file not a directory. This is my fault.
2. Don't run `mongod` as sudo. It doesn't need root access.
3. If this happens again once you have a created a logfile, check the logs for further error messages.

**Comment by themattman** [comment]
If you run without `--fork` as the output says, you should be able to read through the logs and find an error message in there too.
