### ISSUE TITLE
Cannot apt-get update/install packages

### ISSUE THREAD

**Issue by Asleep123** [themattman/mongodb-raspberrypi-binaries#5]
**Describe the bug**
Cannot install packages/do apt-get update without errors.

**To Reproduce**
1. Get all the way to the apt-get update part
2. Returns 404 for some repos
3. Following command doesn't work.

**Expected behavior**
Was supposed to install packages, but got 404s for the following repos when doing apt-get update.
```
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy/main/binary-arm64/Packages  404  Not Found
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/jammy-security/main/binary-arm64/Packages  404  Not Found
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy-updates/main/binary-arm64/Packages  404  Not Found
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy-backports/main/binary-arm64/Packages  404  Not Found

root@DESKTOP-XXXXXXX:/home/asleep# compiler_version=10
root@DESKTOP-XXXXXXX:/home/asleep# sudo apt-get install -y gcc-${compiler_version}-aarch64-linux-gnu g++-${compiler_version}-aarch64-linux-gnu python3-venv
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package gcc-10-aarch64-linux-gnu is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'gcc-10-aarch64-linux-gnu' has no installation candidate
E: Unable to locate package g++-10-aarch64-linux-gnu
E: Couldn't find any package by regex 'g++-10-aarch64-linux-gnu'
```

**Screenshots**

**MongoDB (please complete the following information):**
  - Version: 7.0.6

**Raspberry Pi Device (please complete the following information):**
 - Raspberry Pi Hardware Version: 4B
 - OS: Ubuntu 22.04
 - Version [e.g. 11]
 - System Version [e.g. 32-bit, 64-bit]

**Compilation Machine (please complete the following information):**
 - OS: Ubuntu WSL
 - Version 20.04

**Additional context**

**Comment by themattman** [comment]
Hi @Asleep123,

Are you trying to cross-compile on Windows yourself? The steps required are quite involved, so I would recommend going to the [releases page](https://github.com/themattman/mongodb-raspberrypi-binaries/releases) and download the binaries directly instead. What is MongoDB version `7.0.6`? The highest released version is currently `7.0.3`.

Please explain what you are trying to do and I might be able to help.

**Comment by themattman** [comment]
It's confusing from your description that you've updated the packages to `jammy` (i.e. `22.04`), yet you're compiling on 20.04.

**Comment by Asleep123** [comment]
Wait. I had no idea there were prebuilt binaries. I used the guide in the README.md for the prebuilt ones, and upon running the mongod command, I get the following error. Using Ubuntu 22.04 on a RPI4 8gb ram
```
$ ./mongod --dbpath /data/db/test_db --fork --logpath /data/db/test_db/mongod.log --port 28080
./mongod: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by themattman** [comment]
See [this issue](https://github.com/themattman/mongodb-raspberrypi-binaries/issues/2) for a solution.

**Comment by Asleep123** [comment]
Thanks! How can I stop the server?

**Comment by Asleep123** [comment]
Or make it a systemctl service

**Comment by themattman** [comment]
From the mongo shell [this command](https://www.mongodb.com/docs/manual/reference/method/db.shutdownServer/). To be more forceful, you can `kill -15`.

Systemctl info [here](https://www.mongodb.com/docs/manual/administration/configuration/).
