### ISSUE TITLE
GLIBCXX_3.4.29 and CXXABI_1.3.13' not found (required by ./mongod)

### ISSUE THREAD

**Issue by tomasmark79** [themattman/mongodb-raspberrypi-binaries#9]
Hello! 

I'm trying to deploy latest version of your build but I was facing with a:

**Describe the bug**
./mongod --dbpath /data/db/test_db --fork --logpath /data/db/test_db/mongod.log --port 28080

answer:
./mongod: /lib/aarch64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by ./mongod)
./mongod: /lib/aarch64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./mongod)

My rpi 4 distro:
uname -a
Linux evoboxmark 6.1.32-v8+ #1656 SMP PREEMPT Wed Jun  7 11:37:17 BST 2023 aarch64 GNU/Linux

**Comment by themattman** [comment]
Did you read the [release notes](https://github.com/themattman/mongodb-raspberrypi-binaries/releases/tag/r7.0.5-rpi-unofficial), specifically the section titled "Notes"? If that doesn't work, explain what you're seeing.

**Comment by tomasmark79** [comment]
Great answer. Thank you very much for hint.
